version: 0.0
os: linux
files:
  - source: ap.war
    destination: /opt/tomcat/webapps
permissions:
  - object: /opt/tomcat/webapps/ap.war
    owner: tomcat
    group: tomcat
file_exists_behavior: OVERWRITE
