#=====================================================
# fasthelp&ccs API Properties
#=====================================================
host.protocol=http
host.fasthelp.ip=t2-sec-fasthelp-lb-am.sbisec.int
host.ccs.ip=t2-sec-ccs-lb-cn.sbisec.int
#host.ccs.ip=t2-sec-ccs-lb-cn.sbisec.int,t2-sec-ccs-lb-bn.sbisec.int,t2-sec-ccs-lb-an.sbisec.int
#local devp use it
#host.ccs.ip=t2-zeroccs-uat3.sbisec.int
host.port=80

http.client.connectTimeout=3
http.client.readTimeout=15
http.client.writeTimeout=15
http.client.connPoolTimeout=10
http.client.connPoolCachedMax=5
http.client.retryCount=0