#=====================================================
# Athena API Properties
#=====================================================
host.protocol=https
host.ip=t2-papy.sbisec.int
host.port=443

http.client.connectTimeout=3
http.client.readTimeout=15
http.client.writeTimeout=15
http.client.connPoolTimeout=10
http.client.connPoolCachedMax=5
http.client.retryCount=0

keystore.filepath=/etc/pki/java/cacerts
keystore.password=changeit
