#=====================================================
# POM API Properties
#=====================================================
host.protocol=http
host.ip=127.0.0.1
host.port=3001

http.client.connectTimeout=3
http.client.readTimeout=15
http.client.writeTimeout=15
http.client.connPoolTimeout=10
http.client.connPoolCachedMax=5
http.client.retryCount=2