#=====================================================
# Safe API Properties
#=====================================================
host.protocol=https
#uat1
#host.ip=5kz4kl11k2-vpce-0ed6fe45f8c1d2588.execute-api.ap-northeast-1.amazonaws.com
#uat2
#host.ip=5xcjvz2ec5-vpce-0ed6fe45f8c1d2588.execute-api.ap-northeast-1.amazonaws.com
#uat3
#host.ip=o5fv2ndxs8-vpce-0ed6fe45f8c1d2588.execute-api.ap-northeast-1.amazonaws.com
host.ip=uat3-safe-api.test.c.sbisec.co.jp
host.port=443

http.client.connectTimeout=3
http.client.readTimeout=15
http.client.writeTimeout=15
http.client.connPoolTimeout=10
http.client.connPoolCachedMax=5
http.client.retryCount=0

#local conf
#host.protocol=http
#host.ip=t2-sec-safe-apilb-c.sbisec.int
#host.port=32001
#dummy.safe.env=local