#=====================================================
# Athena API Properties
#=====================================================
host.protocol=http
host.ip=ss.allain.nri.com,allain-sbin.nri.com
host.port=80

http.client.connectTimeout=3
http.client.readTimeout=5
http.client.writeTimeout=10
http.client.connPoolTimeout=10
http.client.connPoolCachedMax=5
http.client.retryCount=1

