version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Vue.js application..."
      - npm run build:prod
      
artifacts:
  files:
    - 'dist/**/*'
  name: artifact
  discard-paths: no